version: '3.7'
services:
  api:
    build: .
    ports:
    - "3001:3001"
    volumes:
    - .:/usr/src/app
    depends_on:
      - redis
    environment:
      - REDISURL=redis
      - REDISPORT=6379
  redis:
    image: redis
